version: 2
updates:
  - package-ecosystem: "pnpm"    # works for npm, yarn, and pnpm
    directory: "/"              # path where your package.json lives
    schedule:
      interval: "weekly"        # could be daily, weekly, or monthly
    versioning-strategy: increase